language: python
python:
- '3.3'
- '3.4'
- '3.5'
- '3.6'
- 3.6-dev
- 3.7-dev
- nightly
- pypy
script:
- bandit -r legos/nettools.py
- bandit -r legos/tools/*.py
- flake8 legos/nettools.py
- flake8 legos/tools/*.py
notifications:
  irc: irc.0x00sec.org#legobot
  on_success: change
  on_failure: always
  use_notice: true
deploy:
  provider: pypi
  user: briggsb
  password:
    secure: Uj1AdIsSiYwK82DMaBtu3VW368ynazXrVivjJG6MkvuSM5wsAmKaTuY2bpvkF4BvhYbA0o+lVTgWoje/keGh8USEu3ULy0LFIeEWiyJbwHzMd9TFzQueBultcmtsJTUGjdXZFVLvbEKEhNFLlArsg3wWNC+JAqAkLpmOBa9zCkU4bJTpuntmjVuNTSOtd9m+nYj3Xg3IxewvH33XOfJyHlg1Myp/7BBMDx09BRp0/Ak6TkbyjQAI0WYIkLDPNDVCYq0N/6bu+38MLMCzahyChz9wYWMPHi6Qc0tGuA31g3c+yXuQggIBX7sPuJKGWL+wYbfKD/r5K357GOjzyOHODvbhsOlBNReMbUS1Ig43A+y1bBL3deknryKbF9yK6qt0SWiUaLhVyaj6PdGmXh5Q0G/nLeQRZ6DTjca8/gIwmn8KkpWO+pJfvapxeiYX7oBCeflFh7a0ecVgIdMePGiv6Hz4hs1GyKXNMAhW6ZTi3zGm4KY9I3Twcl6bUxGYf16j4JQrYFizc0S37xGj/Y+ovIdBgXrbFLz+aI+Fc7Mvu5h1l6uajComgW6B8e+QEjidFhQjZSObatf/oVAsy4wSiIkeBc8Xw8SaI0qkAjKrwpWLiA72VENTaY1cZX6FTyLnqNg5ZphrVm6VWsWz+Iu/RgXiKTXYI30LPj25/3icxsU=
  on:
    tags: true
    distributions: sdist bdist_wheel
